# Generated by Django 5.2.5 on 2025-08-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Catégorie')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='Icône')),
                ('color', models.CharField(blank=True, max_length=20, verbose_name='Couleur')),
                ('legal_reference', models.TextField(blank=True, verbose_name='Référence légale')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Attribution',
                'verbose_name_plural': 'Attributions',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de page',
                'verbose_name_plural': 'Catégories de pages',
            },
        ),
        migrations.CreateModel(
            name='CabinetMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('position', models.CharField(max_length=200, verbose_name='Poste')),
                ('biography', models.TextField(blank=True, verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cabinet_photos', to='media_library.media')),
            ],
            options={
                'verbose_name': 'Membre du cabinet',
                'verbose_name_plural': 'Membres du cabinet',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('name', models.CharField(max_length=200, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('director', models.CharField(blank=True, max_length=200, verbose_name='Directeur')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_logos', to='media_library.media')),
            ],
            options={
                'verbose_name': 'Département',
                'verbose_name_plural': 'Départements',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('name', models.CharField(max_length=200, verbose_name='Nom complet')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('biography', models.TextField(verbose_name='Biographie')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('is_current', models.BooleanField(default=True, verbose_name='Ministre actuel')),
                ('photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='minister_photos', to='media_library.media')),
            ],
            options={
                'verbose_name': 'Ministre',
                'verbose_name_plural': 'Ministres',
            },
        ),
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Nom de l'icône (ex: shield, users, etc.)", max_length=50, verbose_name='Icône')),
                ('color', models.CharField(blank=True, help_text='Code couleur hexadécimal (ex: #FF5733)', max_length=20, verbose_name='Couleur')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mission_images', to='media_library.media')),
            ],
            options={
                'verbose_name': 'Mission',
                'verbose_name_plural': 'Missions',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('language', models.CharField(choices=[('fr', 'Français'), ('en', 'Anglais')], default='fr', max_length=2, verbose_name='Langue')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='Sous-titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('excerpt', models.TextField(blank=True, verbose_name='Extrait')),
                ('meta_title', models.CharField(blank=True, max_length=100, verbose_name='Titre SEO')),
                ('meta_description', models.TextField(blank=True, verbose_name='Description SEO')),
                ('published', models.BooleanField(default=False, verbose_name='Publié')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('show_in_menu', models.BooleanField(default=False, verbose_name='Afficher dans le menu')),
                ('menu_title', models.CharField(blank=True, max_length=100, verbose_name='Titre dans le menu')),
                ('banner_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_banner_images', to='media_library.media')),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_featured_images', to='media_library.media')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='pages.page')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='pages.pagecategory')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
                ('background_color', models.CharField(blank=True, max_length=20, verbose_name='Couleur de fond')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_images', to='media_library.media')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='pages.page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ['order'],
            },
        ),
    ]
