# Generated by Django 5.2.5 on 2025-08-14 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('name', models.CharField(max_length=100, verbose_name='Nom')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Catégorie de médias',
                'verbose_name_plural': 'Catégories de médias',
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/', verbose_name='Fichier')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('video', 'Vidéo'), ('audio', 'Audio')], max_length=20, verbose_name='Type de média')),
                ('alt_text', models.CharField(blank=True, help_text='Texte alternatif pour les images (accessibilité)', max_length=255, verbose_name='Texte alternatif')),
                ('copyright', models.CharField(blank=True, max_length=255, verbose_name='Copyright')),
                ('featured', models.BooleanField(default=False, verbose_name='Mis en avant')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media', to='media_library.mediacategory')),
            ],
            options={
                'verbose_name': 'Média',
                'verbose_name_plural': 'Médias',
            },
        ),
    ]
